import type { Metadata } from "next";
import { Noto Serif Bengali } from "next/font/google";
import "./globals.css";

const notoSerifBengoli = Noto Serif Bengali({
 
  subsets: ["latin","bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
